### ISSUE TITLE
Grails 4.0.0 Sequence-per-table configuration

### ISSUE THREAD

**Issue by Noxville** [kaleidos/grails-postgresql-extensions#124]
According to the installation guide it says:

```
For Hibernate 5 add the following to application.groovy

grails.gorm.default.mapping = {
    id generator: 'org.hibernate.id.enhanced.SequenceStyleGenerator', params: [prefer_sequence_per_entity: true]
}
```

This seems a bit weird/outdated/incorrect since my application.groovy looks like a spring boot boilerplate main (https://gist.github.com/Noxville/1a5232908f2fd19296261607a7244435).

**Comment by ilopmar** [comment]
That comment refers to `./grails-app/conf/application.groovy` and not `./grails-app/init/.../Application.groovy`

**Comment by ilopmar** [comment]
Fixed by @erichelgeson in https://github.com/kaleidos/grails-postgresql-extensions/pull/125

**Comment by Noxville** [comment]
Hey there, thanks for that fix @ilopmar, however even with that I'm still not seeing correctly generated sequences per table. Here's a gist with the relevant files: https://gist.github.com/Noxville/87e583d9a4340804a15afc75a87b0a81

**Comment by ilopmar** [comment]
@Noxville I haven't tried it with Grails 4. TBH I don't use it now but I keep maintaining it and merging PR from the community.

@erichelgeson have you tried the plugins with Grails 4 and the sequence per table?
